functional:
  - Пользователь может создать аккаунт и войти в систему с помощью email и пароля
  - Два пользователя могут начать соревнование в реальном времени и видеть процесс написания кода друг друга
  - Пользователь может сыграть с ботом, выбрав уровень сложности
  - Пользователь может пригласить друга по ссылке для игры
  - Система проверяет корректность решения задачи и определяет победителя
  - Результаты игр сохраняются, и формируется персональный рейтинг пользователя
  - Пользователь может просматривать историю своих игр
  - Администратор может добавлять, редактировать или удалять задачи для соревнований

non-functional:
  - Сайт должен загружаться за время не более 2 секунд при среднем соединении (3G)
  - Интерфейс должен быть адаптирован для мобильных устройств (с поддержкой сенсорного ввода)
  - Приложение должно поддерживать последние версии Chrome, Firefox, Safari и Edge
  - Данные пользователей должны храниться в зашифрованном виде, а авторизация — реализована с использованием безопасных протоколов (например, OAuth, JWT)
  - Система должна корректно работать при одновременном подключении не менее 1000 пользователей
  - Приложение должно обеспечивать непрерывную работу (доступность не менее 99.9% в месяц)

implicit:
  - Интерфейс должен быть интуитивно понятным и не требовать обучения
  - Ошибки ввода должны отображаться понятным языком с подсказками по исправлению
  - Код, написанный одним игроком, должен отображаться другому с минимальной задержкой (до 500 мс)
  - Приложение должно работать стабильно при кратковременных потерях соединения (с возможностью восстановления сессии)
  - Текст на сайте должен быть доступен для скринридеров (базовая доступность)
  - Названия задач и интерфейс должны быть на английском языке (по умолчанию), с возможностью локализации
